### PR TITLE
Show signing fields if address is required

### LINKED ISSUE #541: Signing fails when logged in user does not have address
When a user is logged in, but session.json does not report having a full local address (i.e. `potential_addresses: [status: "Potential"]` is NOT present), and the petition requires an address, then clicking 'Sign' doesn't do anything.  This is presumably because validation is trying to report that there is no address, but reporting that near the address fields which are hidden when someone is logged in.

Instead, address fields should be shown if someone is not logged in OR (when it is a local petition AND they don't have a potential address on file )

My guess is this was introduced when we hid the additional fields by default and only show them once someone starts typing.

### PR DESCRIPTION
**Pull request by jparkrr**
first, show all the fields after there is a validation error

second, always show all the fields if the user doesn't have an address and the petiton needs one

fixes #541

### CODE REVIEW

**Comment by jparkrr** [comment]
Hmmm. I guess it should only show the address on needs_full_addresses if you are logged in, and keep them hidden at first if you are logged out (since you already have to type something)

**Comment by jparkrr** [comment]
Hm, @schuyler1d said in #544 
> Instead, address fields should be shown if someone is not logged in OR (when it is a local petition AND they don't have a potential address on file )

File: test/components/signature-add-form.js [hunk 1]
```diff
@@ -36,6 +43,12 @@ describe('<SignatureAddForm />', () => {
     token: 'akid:fake.123456.bad123',
     given_name: 'Three Stacks' } }
 
+  const storeAkidAddress = { userStore: { signonId: 123456,
+      token: 'akid:fake.123456.bad123',
+      given_name: 'Three Stacks',
+      postal_addresses: ['some address']
```
Comment (schuyler1d) [inline test/components/signature-add-form.js]: this is actually an array of dicts, so it doesn't matter, but it might be good to represent what it would actually look like: `postal_addresses: [{status: 'Potential'}]`
